## Nama : Muhammad Naufal Wildan
## NIM    : 2009106037
## Kelas : Informatika A 2020


## POSTTEST 4 KB

In [17]:
import pandas as pd
import seaborn as sns
import numpy as np 
from sklearn.model_selection import train_test_split

In [61]:
df = pd.read_csv("international_matches.csv")

In [62]:
df

date       home_team     away_team home_team_continent  \
0      1993-08-08             NaN       Uruguay       South America   
1      1993-08-08             NaN        Mexico       South America   
2      1993-08-08             NaN     Venezuela       South America   
3      1993-08-08             NaN  Sierra Leone              Africa   
4      1993-08-08             NaN     Argentina       South America   
...           ...             ...           ...                 ...   
23917  2022-06-14         Moldova       Andorra              Europe   
23918  2022-06-14   Liechtenstein        Latvia              Europe   
23919  2022-06-14           Chile         Ghana       South America   
23920  2022-06-14           Japan       Tunisia                Asia   
23921  2022-06-14  Korea Republic         Egypt                Asia   

      away_team_continent  home_team_fifa_rank  away_team_fifa_rank  \
0           South America                   59                   22   
1           North America                    8                   14   
2           South America                   35                   94   
3                  Africa                   65                   86   
4           South America                   67                    5   
...                   ...                  ...                  ...   
23917              Europe                  180                  153   
23918              Europe                  192                  135   
23919              Africa                   28                   60   
23920              Africa                   23                   35   
23921              Africa                   29                   32   

       home_team_total_fifa_points  away_team_total_fifa_points  \
0                                0                            0   
1                                0                            0   
2                                0                            0   
3                                0                            0   
4                                0                            0   
...                            ...                          ...   
23917                          932                         1040   
23918                          895                         1105   
23919                         1526                         1387   
23920                         1553                         1499   
23921                         1519                         1500   

       home_team_score  ...  shoot_out home_team_result  \
0                    3  ...         No              Win   
1                    1  ...         No             Draw   
2                    5  ...         No              Win   
3                    1  ...         No              Win   
4                    1  ...         No             Lose   
...                ...  ...        ...              ...   
23917                2  ...         No              Win   
23918                0  ...         No             Lose   
23919                0  ...        Yes             Lose   
23920                0  ...         No             Lose   
23921                4  ...         No              Win   

      home_team_goalkeeper_score away_team_goalkeeper_score  \
0                            NaN                        NaN   
1                            NaN                        NaN   
2                            NaN                        NaN   
3                            NaN                        NaN   
4                            NaN                        NaN   
...                          ...                        ...   
23917                       65.0                        NaN   
23918                        NaN                       65.0   
23919                       79.0                       74.0   
23920                       73.0                        NaN   
23921                       75.0                        NaN   

       home_team_mean_defense_score 

In [63]:
df.isna().sum()

date                                 0
home_team                            7
away_team                            0
home_team_continent                  0
away_team_continent                  0
home_team_fifa_rank                  0
away_team_fifa_rank                  0
home_team_total_fifa_points          0
away_team_total_fifa_points          0
home_team_score                      0
away_team_score                      0
tournament                           0
city                                 0
country                              0
neutral_location                     0
shoot_out                            0
home_team_result                     0
home_team_goalkeeper_score       15543
away_team_goalkeeper_score       15827
home_team_mean_defense_score     16135
home_team_mean_offense_score     15412
home_team_mean_midfield_score    15760
away_team_mean_defense_score     16358
away_team_mean_offense_score     15610
away_team_mean_midfield_score    15943
dtype: int64

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23922 entries, 0 to 23921
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   date                           23922 non-null  object 
 1   home_team                      23915 non-null  object 
 2   away_team                      23922 non-null  object 
 3   home_team_continent            23922 non-null  object 
 4   away_team_continent            23922 non-null  object 
 5   home_team_fifa_rank            23922 non-null  int64  
 6   away_team_fifa_rank            23922 non-null  int64  
 7   home_team_total_fifa_points    23922 non-null  int64  
 8   away_team_total_fifa_points    23922 non-null  int64  
 9   home_team_score                23922 non-null  int64  
 10  away_team_score                23922 non-null  int64  
 11  tournament                     23922 non-null  object 
 12  city                           23922 non-null 

## Training set 70 : Testing set 30

In [65]:
X = df.iloc[:,:-1] 
Y = df.iloc[:,-1] 

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [67]:
print("Dimensi X_train : ", X_train.shape)
print("Dimensi X_train : ", X_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test : ", X_test.shape)

Dimensi X_train :  (16745, 24)
Dimensi X_train :  (7177, 24)
Dimensi y_train :  (16745,)
Dimensi y_test :  (7177, 24)


## Normalisasi

In [68]:
from sklearn.preprocessing import MinMaxScaler

In [69]:
mm = MinMaxScaler()
x_scaled = mm.fit_transform(
df[['home_team_fifa_rank','home_team_total_fifa_points','home_team_score']])

In [70]:
normalisasi = pd.DataFrame(x_scaled)
normalisasi.head()

0    1         2
0  0.276190  0.0  0.096774
1  0.033333  0.0  0.032258
2  0.161905  0.0  0.161290
3  0.304762  0.0  0.032258
4  0.314286  0.0  0.032258

## Standarisasi

In [71]:
from sklearn.preprocessing import StandardScaler

In [72]:
SS = StandardScaler()
data = np.asarray(df[['home_team_fifa_rank','home_team_total_fifa_points','home_team_score']])
Scaled = ss.fit_transform(data)

In [73]:
print("Nilai Data Sebelum scaling : ") 
print(data) 
print("Nilai standar deviasi: ", np.std(data))
print("============================================")
print("\n Nilai Data setelah scaling : ") 
print(Scaled) 
print("Nilai standar deviasi: ", np.std(Scaled)) 

Nilai Data Sebelum scaling : 
[[  59    0    3]
 [   8    0    1]
 [  35    0    5]
 ...
 [  28 1526    0]
 [  23 1553    0]
 [  29 1519    4]]
Nilai standar deviasi:  321.5066055346922

 Nilai Data setelah scaling : 
[[-0.36028081 -0.64573095  0.85311283]
 [-1.3344835  -0.64573095 -0.37378179]
 [-0.81872913 -0.64573095  2.08000745]
 ...
 [-0.95244323  2.40133796 -0.9872291 ]
 [-1.04795329  2.45525071 -0.9872291 ]
 [-0.93334121  2.38736058  1.46656014]]
Nilai standar deviasi:  1.0


## Data Cleaning

In [74]:
from sklearn.impute import SimpleImputer

In [75]:
df.isna().sum()

date                                 0
home_team                            7
away_team                            0
home_team_continent                  0
away_team_continent                  0
home_team_fifa_rank                  0
away_team_fifa_rank                  0
home_team_total_fifa_points          0
away_team_total_fifa_points          0
home_team_score                      0
away_team_score                      0
tournament                           0
city                                 0
country                              0
neutral_location                     0
shoot_out                            0
home_team_result                     0
home_team_goalkeeper_score       15543
away_team_goalkeeper_score       15827
home_team_mean_defense_score     16135
home_team_mean_offense_score     15412
home_team_mean_midfield_score    15760
away_team_mean_defense_score     16358
away_team_mean_offense_score     15610
away_team_mean_midfield_score    15943
dtype: int64

## Ubah nilai NULL yang memiliki tipe data desimal

In [76]:
imputer = SimpleImputer(strategy = 'mean')
df["home_team_goalkeeper_score"] = imputer.fit_transform(df[["home_team_goalkeeper_score"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
date                                 0
home_team                            7
away_team                            0
home_team_continent                  0
away_team_continent                  0
home_team_fifa_rank                  0
away_team_fifa_rank                  0
home_team_total_fifa_points          0
away_team_total_fifa_points          0
home_team_score                      0
away_team_score                      0
tournament                           0
city                                 0
country                              0
neutral_location                     0
shoot_out                            0
home_team_result                     0
home_team_goalkeeper_score           0
away_team_goalkeeper_score       15827
home_team_mean_defense_score     16135
home_team_mean_offense_score     15412
home_team_mean_midfield_score    15760
away_team_mean_defense_score     16358
away_team_mean_offense_score     15610
away_team_mean_

## Ubah nilai NULL yang memiliki tipe data kategorikal

In [77]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["home_team"] = imputer.fit_transform(df[["home_team"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
date                                 0
home_team                            0
away_team                            0
home_team_continent                  0
away_team_continent                  0
home_team_fifa_rank                  0
away_team_fifa_rank                  0
home_team_total_fifa_points          0
away_team_total_fifa_points          0
home_team_score                      0
away_team_score                      0
tournament                           0
city                                 0
country                              0
neutral_location                     0
shoot_out                            0
home_team_result                     0
home_team_goalkeeper_score           0
away_team_goalkeeper_score       15827
home_team_mean_defense_score     16135
home_team_mean_offense_score     15412
home_team_mean_midfield_score    15760
away_team_mean_defense_score     16358
away_team_mean_offense_score     15610
away_team_mean_

## Ubah nilai NULL yang memiliki tipe data bilang bulat

In [78]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["away_team_mean_midfield_score"] = imputer.fit_transform(df[["away_team_mean_midfield_score"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
date                                 0
home_team                            0
away_team                            0
home_team_continent                  0
away_team_continent                  0
home_team_fifa_rank                  0
away_team_fifa_rank                  0
home_team_total_fifa_points          0
away_team_total_fifa_points          0
home_team_score                      0
away_team_score                      0
tournament                           0
city                                 0
country                              0
neutral_location                     0
shoot_out                            0
home_team_result                     0
home_team_goalkeeper_score           0
away_team_goalkeeper_score       15827
home_team_mean_defense_score     16135
home_team_mean_offense_score     15412
home_team_mean_midfield_score    15760
away_team_mean_defense_score     16358
away_team_mean_offense_score     15610
away_team_mean_

## Data duplikat

In [79]:
df[df.duplicated()]

date      home_team     away_team home_team_continent  \
99   1993-08-08         Mexico  Sierra Leone              Africa   
100  1993-08-08         Mexico     Argentina       South America   
101  1993-08-08           Peru      Colombia       South America   
102  1993-08-08       Zimbabwe      Eswatini              Africa   
103  1993-08-09         Guinea  Sierra Leone              Africa   
104  1993-08-11  Faroe Islands        Norway              Europe   

    away_team_continent  home_team_fifa_rank  away_team_fifa_rank  \
99               Africa                   65                   86   
100       South America                   67                    5   
101       South America                   70                   19   
102              Africa                   50                  102   
103              Africa                   65                   86   
104              Europe                  111                    9   

     home_team_total_fifa_points  away_team_total_fifa_points  \
99                             0                            0   
100                            0                            0   
101                            0                            0   
102                            0                            0   
103                            0                            0   
104                            0                            0   

     home_team_score  ...  shoot_out home_team_result  \
99                 1  ...         No              Win   
100                1  ...         No             Lose   
101                0  ...         No             Lose   
102                2  ...         No              Win   
103                4  ...         No              Win   
104                0  ...         No             Lose   

    home_team_goalkeeper_score away_team_goalkeeper_score  \
99                   74.963838                        NaN   
100                  74.963838                        NaN   
101                  74.963838                        NaN   
102                  74.963838                        NaN   
103                  74.963838                        NaN   
104                  74.963838                        NaN   

     home_team_mean_defense_score home_team_mean_offense_score  \
99                            NaN                          NaN   
100                           NaN                          NaN   
101                           NaN                          NaN   
102                           NaN                          NaN   
103                           NaN                          NaN   
104                           NaN                          NaN   

    home_team_mean_midfield_score  away_team_mean_defense_score  \
99                            NaN                           NaN   
100                           NaN                           NaN   
101                           NaN                           NaN   
102                           NaN                           NaN   
103                           NaN                           NaN   
104                           NaN                           NaN   

     away_team_mean_offense_score  away_team_mean_midfield_score  
99                            NaN                           76.2  
100                           NaN                           76.2  
101                           NaN                           76.2  
102                           NaN                           76.2  
103                           NaN                           76.2  
104                           NaN                           76.2  

[6 rows x 25 columns]

In [80]:
df.drop_duplicates(inplace=True)

In [81]:
print("Setelah menggunakan fungsi drop_duplicates()") 
print("Jumlah Nilai Duplikat:",df.duplicated().sum())

Setelah menggunakan fungsi drop_duplicates()
Jumlah Nilai Duplikat: 0


## Ubah tipe data angka menjadi kategorikal

In [82]:
from sklearn.preprocessing import OrdinalEncoder 

In [83]:
encoder = OrdinalEncoder() 
df["date"] = encoder.fit_transform(df[["date"]]) 
df.head()

date home_team     away_team home_team_continent away_team_continent  \
0   0.0    Mexico       Uruguay       South America       South America   
1   0.0    Mexico        Mexico       South America       North America   
2   0.0    Mexico     Venezuela       South America       South America   
3   0.0    Mexico  Sierra Leone              Africa              Africa   
4   0.0    Mexico     Argentina       South America       South America   

   home_team_fifa_rank  away_team_fifa_rank  home_team_total_fifa_points  \
0                   59                   22                            0   
1                    8                   14                            0   
2                   35                   94                            0   
3                   65                   86                            0   
4                   67                    5                            0   

   away_team_total_fifa_points  home_team_score  ...  shoot_out  \
0                            0                3  ...         No   
1                            0                1  ...         No   
2                            0                5  ...         No   
3                            0                1  ...         No   
4                            0                1  ...         No   

  home_team_result home_team_goalkeeper_score away_team_goalkeeper_score  \
0              Win                  74.963838                        NaN   
1             Draw                  74.963838                        NaN   
2              Win                  74.963838                        NaN   
3              Win                  74.963838                        NaN   
4             Lose                  74.963838                        NaN   

   home_team_mean_defense_score home_team_mean_offense_score  \
0                           NaN                          NaN   
1                           NaN                          NaN   
2                           NaN                          NaN   
3                           NaN                          NaN   
4                           NaN                          NaN   

  home_team_mean_midfield_score  away_team_mean_defense_score  \
0                           NaN                           NaN   
1                           NaN                           NaN   
2                           NaN                           NaN   
3                           NaN                           NaN   
4                           NaN                           NaN   

   away_team_mean_offense_score  away_team_mean_midfield_score  
0                           NaN                           76.2  
1                           NaN                           76.2  
2                           NaN                           76.2  
3                           NaN                           76.2  
4                           NaN                           76.2  

[5 rows x 25 columns]

## One Hot Encoding

In [84]:
from sklearn.preprocessing import OneHotEncoder 

In [87]:
encoder = OneHotEncoder(sparse=False) 
home_team_scoreEnc = encoder.fit_transform(df[["home_team_score"]]) 
home_team_scoreEnc = pd.DataFrame(home_team_scoreEnc) 
df = df.join(home_team_scoreEnc) 
df 

date       home_team     away_team home_team_continent  \
0         0.0          Mexico       Uruguay       South America   
1         0.0          Mexico        Mexico       South America   
2         0.0          Mexico     Venezuela       South America   
3         0.0          Mexico  Sierra Leone              Africa   
4         0.0          Mexico     Argentina       South America   
...       ...             ...           ...                 ...   
23917  5545.0         Moldova       Andorra              Europe   
23918  5545.0   Liechtenstein        Latvia              Europe   
23919  5545.0           Chile         Ghana       South America   
23920  5545.0           Japan       Tunisia                Asia   
23921  5545.0  Korea Republic         Egypt                Asia   

      away_team_continent  home_team_fifa_rank  away_team_fifa_rank  \
0           South America                   59                   22   
1           North America                    8                   14   
2           South America                   35                   94   
3                  Africa                   65                   86   
4           South America                   67                    5   
...                   ...                  ...                  ...   
23917              Europe                  180                  153   
23918              Europe                  192                  135   
23919              Africa                   28                   60   
23920              Africa                   23                   35   
23921              Africa                   29                   32   

       home_team_total_fifa_points  away_team_total_fifa_points  \
0                                0                            0   
1                                0                            0   
2                                0                            0   
3                                0                            0   
4                                0                            0   
...                            ...                          ...   
23917                          932                         1040   
23918                          895                         1105   
23919                         1526                         1387   
23920                         1553                         1499   
23921                         1519                         1500   

       home_team_score  ...   11   12   13   14   15   16   17   18   19   20  
0                    3  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1                    1  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2                    5  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3                    1  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4                    1  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...                ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
23917                2  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
23918                0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
23919                0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
23920                0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
23921                4  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[23916 rows x 46 columns]